name: Sync plugins.json to README

on:
  push:
    paths:
      - 'plugins.json'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run sync script
        run: node scripts/sync-readme.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: sync README from plugins.json [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
